export const xboxgames = [
    {
      id:1,
      img:"https://www.gamecards.net/wp-content/uploads/2020/07/Ghost-of-Tsushima-ps4.jpg",
      title: "Ghost Of Tsushima - PS4",
      price: 3000,
      description: "<p>It’s the late 13th century, and the Mongol empire has laid waste to entire nations in its campaign to conquer the East. Tsushima Island is all that stands between mainland Japan and a massive Mongol invasion. <br>As the island burns in the wake of the first wave of the Mongol assault, samurai warrior Jin Sakai resolves to do whatever it takes to protect his people and reclaim his home. <br>• Beyond war, ancient beauty endures: Uncover the hidden wonders of Tsushima in this open-world action adventure. <br>• The rise of the Ghost: Forge a new path and wage an unconventional war for the freedom of Tsushima. <br>• Mud, blood and steel: Challenge opponents with your katana for an immersive samurai combat experience, master the bow to eliminate distant threats and develop stealth tactics to ambush enemies.</p>",
      promo: "https://www.youtube.com/embed/0HTfLqHoTmg",
      details: "<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 24.5 hours, Main + Extra - 43 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>Optional </div> <br> <div> <strong>Metacritic Review Score: </strong> 83/100 </div> <div> <strong>Release Date: </strong>17 Jul 2020 </div> <div> <strong>Developer: </strong> Sucker Punch Productions </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Product sourced from Individual in India as a pre-owned one </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "NEW",
      other_loc:13,
      device:"PS4",
    },
    {
      id:2,
      img:"https://rukminim2.flixcart.com/image/416/416/kr3tj0w0/physical-game/c/f/u/standard-edition-ps4-minecraft-starter-collection-full-game-ps4-original-imag4ypx2qajzfgq.jpeg?q=70",
      title:"Minecraft Bedrock Edition - PS4",
      price:2000,
      description:"<p>Explore randomly generated worlds and build amazing things from the simplest of homes to the grandest of castles. Play in creative mode with unlimited resources or mine deep into the world in survival mode, crafting weapons and armour to fend off the dangerous mobs.</p>",
      promo:"https://www.youtube.com/embed/5QYaQw0cQYI",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Adventure / Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 123 hours, Main + Extra - 281 hours </div> <div> <strong>Internet Requirement: </strong>Yes </div> <div> <strong>PS Plus Requirement: </strong>Optional </div> <br> <div> <strong>Metacritic Review Score: </strong> 89/100 </div> <div> <strong>Release Date: </strong>05 Sep 2014 </div> <div> <strong>Developer: </strong> Mojang Studios </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Sweden </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 7 and over </div> </div>",
      condition: "NEW",
      other_loc:14,
      device:"PS4",
    },
    {
      id:3,
      img:"https://rukminim2.flixcart.com/image/416/416/kw5ag7k0/physical-game/t/k/m/-original-imag8w4bg6mfssuh.jpeg?q=70",
      title:"God Of War - PS4",
      price:1500,
      description:"<p>Living as a man outside the shadow of the gods, Kratos must adapt to unfamiliar lands, unexpected threats and a second chance at being a father. Together with his son Atreus, the pair will venture into the brutal realm of Midgard and fight to fulfil a deeply personal quest. <br>• Journey to a dark, elemental world of fearsome creatures – straight from the pages of Norse mythology. <br>• Conquer your foes in vicious close-quarters combat that rewards tactical thinking and lethal precision. <br>• Discover an emotionally gripping tale of father and son, as Kratos is made to control the rage that has long defined him.</p>",
      promo:"https://www.youtube.com/embed/K0u_kAWLJOA",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 20.5 hours, Main + Extra - 32 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 94/100 </div> <div> <strong>Release Date: </strong>20 Apr 2018 </div> <div> <strong>Developer: </strong> Santa Monica Studio </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "NEW",
      other_loc:15,
      device:"PS4",
    },
    {
      id:4,
      img:"https://rukminim2.flixcart.com/image/416/416/joixj0w0/physical-game/u/3/u/standard-edition-red-dead-redemption-2-full-game-ps4-original-imafayznnszyfn2h.jpeg?q=70",
      title:"Red Dead Redemption 2 - PS4",
      price:2500,
      description:"<p>Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, Red Dead Redemption 2 is an epic tale of honor and loyalty at the dawn of the modern age. <br> <br>America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him. <br> <br>Red Dead Redemption 2 also includes the shared living world of Red Dead Online – forge your own path as you battle lawmen, outlaw gangs and ferocious wild animals to build a life on the American frontier. Build a camp, ride solo or form a posse and explore everything from the snowy mountains in the North to the swamps of the South, from remote outposts to busy farms and bustling towns. Chase down bounties, hunt, fish and trade, search for exotic treasures, run your own underground Moonshine distillery, or become a Naturalist to learn the secrets of the animal kingdom and much more in a world of astounding depth and detail.</p>",
      promo:"https://www.youtube.com/embed/h6k532Y7jK8",
      details:"<div> <div> <strong>Game Type: </strong> Campaign + Multiplayer </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 49 hours, Main + Extra - 78.5 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>Optional </div> <br> <div> <strong>Metacritic Review Score: </strong> 97/100 </div> <div> <strong>Release Date: </strong>26 Oct 2018 </div> <div> <strong>Developer: </strong> Rockstar Games </div> <div> <strong>Publisher: </strong> Rockstar Games </div> <div> <strong>Country of Origin: </strong>United States </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "NEW",
      other_loc:16,
      device:"PS4",
    },
    {
      id:5,
      img:"https://rukminim2.flixcart.com/image/416/416/j5pmt8w0/physical-game/x/n/c/uncharted-the-nathan-drake-collection-ps4-original-imaer6qwcpz2p4qa.jpeg?q=70",
      title:"Uncharted - The Nathan Drake Collection - PS4",
      price:2000,
      description:"<div> <p>Experience one of the most revered game series of all time as you follow the perilous journey of Nathan Drake across the globe, from humble beginnings to extraordinary discoveries. <br> <br>Meet an unforgettable cast of characters as Drake puts life and friendship on the line in a race against ruthless enemies to uncover unimaginable treasures. <br> <br>Uncharted: The Nathan Drake Collection includes the single-player campaigns only for Uncharted: Drake’s Fortune, Uncharted 2: Among Thieves, and Uncharted 3: Drake’s Deception.</p> </div>",
      promo:"https://www.youtube.com/embed/-mH2SVyBMAQ",
      details:"<div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 27 hours, Main + Extra - 31 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 86/100 </div> <div> <strong>Release Date: </strong>07 Oct 2015 </div> <div> <strong>Developer: </strong> Naughty Dog </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "NEW",
      other_loc:17,
      device:"PS4",
    },
    {
      id:6,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1232",
      title:"Assassins Creed Valhalla - PS4",
      price:4000,
      description:"<div> <p>Build your own Viking legend at 60 FPS and in 4K resolution. <br> <br>Become Eivor, a legendary Viking warrior raised on tales of battle and glory. Raid your enemies, grow your settlement, and build your political power in the quest to earn a place among the gods in Valhalla. <br> <br>- Lead epic Viking raids against Saxon troops and fortresses. <br>- Relive the visceral fighting style of the Vikings as you dual-wield powerful weapons. <br>- Challenge yourself with the most varied collection of enemies ever in Assassin's Creed. <br>- Shape the growth of your character and your clan's settlement with every choice you make. <br>- Explore a Dark Age open world, from the harsh shores of Norway to the beautiful kingdoms of England.</p> </div>",
      promo:"https://www.youtube.com/embed/gnmuEkn30ZE",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure / Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 52 hours, Main + Extra - 86 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 84/100 </div> <div> <strong>Release Date: </strong>10 Nov 2020 </div> <div> <strong>Developer: </strong> Ubisoft </div> <div> <strong>Publisher: </strong> Ubisoft </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "NEW",
      other_loc:18,
      device:"PS4",
    },
    {
      id:7,
      img:"https://rukminim2.flixcart.com/image/416/416/jpa2w7k0/physical-game/z/a/d/standard-edition-tekken-7-full-game-ps4-original-imafbjxexwbsnb7j.jpeg?q=70",
      title:"Tekken 7 - PS4",
      price:1700,
      description:"<div> <p>Discover the epic conclusion of the Mishima clan and unravel the reasons behind each step of their ceaseless fight. Powered by Unreal Engine 4, TEKKEN 7 features stunning story-driven cinematic battles and intense duels that can be enjoyed with friends and rivals alike through innovative fight mechanics. <br> <br>Love, Revenge, Pride. Everyone has a reason to fight. Values are what define us and make us human, regardless of our strengths and weaknesses. There are no wrong motivations, just the path we choose to take. <br></p> </div>",
      promo:"https://www.youtube.com/embed/1V-_q3SKh5w",
      details:"<div><div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Fighting </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 3 hours, Main + Extra - 7 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>Optional </div> <br> <div> <strong>Metacritic Review Score: </strong> 82/100 </div> <div> <strong>Release Date: </strong>18 Mar 2015 </div> <div> <strong>Developer: </strong> Bandai Namco Studios </div> <div> <strong>Publisher: </strong> Bandai Namco Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "NEW",
      other_loc:19,
      device:"PS4",
    },
    {
      id:8,
      img:"https://rukminim2.flixcart.com/image/416/416/av-media/games/f/f/m/the-last-of-us-remastered-original-imady9fcv5xe4kbf.jpeg?q=70",
      title:"The Last Of Us Remastered - PS4",
      price:1300,
      description:"<div> <p>In a hostile, post-pandemic world, Joel and Ellie, brought together by desperate circumstances, must rely on each other to survive a brutal journey across what remains of the USA. <br> <br> <br>Remastered Features: <br>• Explore a beautiful, decimated world, fully realised with the power of PlayStation4 in 1080p High Definition. <br>• Delve into Ellie’s past in Left Behind, a single-player prequel chapter. <br>• Fight for survival across the Abandoned and Reclaimed Territories with eight new multiplayer maps and a harder single-player difficulty mode. <br>• Behind-the-scenes in-game cinematic commentary from the cast and creative director.</p> </div>",
      promo:"https://www.youtube.com/embed/ygVPHxkokAE",
      details:"<div><div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 14 hours, Main + Extra - 17 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>Optional </div> <br> <div> <strong>Metacritic Review Score: </strong> 95/100 </div> <div> <strong>Release Date: </strong>14 Jun 2013 </div> <div> <strong>Developer: </strong> Naughty Dog </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Andorra </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "NEW",
      other_loc:20,
      device:"PS4",
    },
    {
      id:9,
      img:"https://rukminim2.flixcart.com/image/416/416/ku1k4280/physical-game/f/s/w/no-complete-edition-horizon-zero-dawn-full-game-ps4-original-imag796pg9f7hqgs.jpeg?q=70",
      title:"Horizon Zero Dawn Complete Edition - PS4",
      price:1000,
      description:"<div> <p>EARTH IS OURS NO MORE <br> <br>Experience Aloy of the Nora’s entire legendary quest to unravel the mysteries of a world ruled by deadly Machines. <br> <br>An outcast from her tribe, the young hunter fights to uncover her past, discover her destiny… and stop a catastrophic threat to the future. <br> <br>Unleash devastating, tactical attacks against unique Machines and rival tribes as you explore an open wold teeming with wildlife and danger. <br> <br>Horizon Zero Dawn™ is a multi-award-winning action role-playing game – and this Complete Edition includes the huge expansion The Frozen Wilds, featuring new lands, skills, weapons and Machines. <br> <br>Enhanced for PlayStation®4 Pro. <br> <br>INCLUDES: <br>• Horizon Zero Dawn. <br>• The Frozen Wilds expansion. <br>• Carja Storm Ranger Outfit and Carja Mighty Bow. <br>• Carja Trader Pack. <br>• Banuk Trailblazer Outfit and Banuk Culling Bow. <br>• Banuk Traveller Pack. <br>• Nora Keeper Pack. <br>• Digital art book. <br>• PS4™ theme. <br> <br>Bonus costumes, weapons and item packs are available after downloading Horizon Zero Dawn: Complete Edition update file version 1.45 otherwise they are unlockable through gameplay.</p> </div>",
      promo:"https://www.youtube.com/embed/6Z1AGyzZbLM",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 31 hours, Main + Extra - 56 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 89/100 </div> <div> <strong>Release Date: </strong>06 Dec 2017 </div> <div> <strong>Developer: </strong> Guerrilla Games </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "NEW",
      other_loc:21,
      device:"PS4",
    },
    {
      id:10,
      img:"https://m.media-amazon.com/images/I/518B2PBNkHL.jpg",
      title:"Marvel's Spiderman - PS4",
      price:2000,
      description:"<div> <p>BE GREATER. <br> <br>Explore a new chapter in Marvel’s Spider-Man universe as a more experienced Peter Parker. <br> <br>Starring one of the world’s most iconic Super Heroes, Marvel's Spider-Man features the acrobatic abilities, improvisation and web-slinging that the wall-crawler is famous for, while also introducing elements never-before-seen in a Spider-Man game. <br> <br>From traversing by parkour and unique environmental interactions, to new combat and blockbuster action, it’s Spider-Man unlike any you’ve played before.</p> </div>",
      promo:"https://www.youtube.com/embed/b5-_MvCWSfI",
      details:"<div><div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 16 hours, Main + Extra - 24.5 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 87/100 </div> <div> <strong>Release Date: </strong>07 Sep 2018 </div> <div> <strong>Developer: </strong> Insomniac Games </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "NEW",
      other_loc:22,
      device:"PS4",
    },
    {
      id:11,
      img:"https://m.media-amazon.com/images/I/71mrNn40chL._SX385_.jpg",
      title:"Elden Ring - PS4",
      price:4000,
      description:"<p>The Golden Order has been broken. <br> <br>In the Lands Between ruled by Queen Marika the Eternal, the Elden Ring, the source of the Erdtree, has been shattered. <br> <br>Marika's offspring, demigods all, claimed the shards of the Elden Ring known as the Great Runes, and the mad taint of their newfound strength triggered a war: The Shattering. A war that meant abandonment by the Greater Will. <br> <br>And now the guidance of grace will be brought to the Tarnished who were spurned by the grace of gold and exiled from the Lands Between. <br> <br>Ye dead who yet live, your grace long lost, follow the path to the Lands Between beyond the foggy sea to stand before the Elden Ring. <br> <br>And become the Elden Lord.</p>",
      promo:"https://www.youtube.com/embed/E3Huy2cdih0",
      details:"<div><div> <strong>Game Type: </strong> Campaign + Multiplayer </div> <div> <strong>Genre: </strong> Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 44 hours, Main + Extra - 74.5 hours </div> <div> <strong>Internet Requirement: </strong>Yes </div> <div> <strong>PS Plus Requirement: </strong>Yes </div> <br> <div> <strong>Metacritic Review Score: </strong> 97/100 </div> <div> <strong>Release Date: </strong>25 Feb 2022 </div> <div> <strong>Developer: </strong> FromSoftware Inc </div> <div> <strong>Publisher: </strong> BANDAI NAMCO ENTERTAINMENT </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "NEW",
      other_loc:23,
      device:"PS4",
    },
    {
      id:12,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_105",
      title:"Marvel's Spider-Man Miles Morales - PS4",
      price:4000,
      description:"In the latest adventure in the Marvel's Spider-Man universe, teenager Miles Morales is adjusting to his new home while following in the footsteps of his mentor, Peter Parker, as a new Spider-Man. But when a fierce power struggle threatens to destroy his new home, the aspiring hero realises that with great power, there must also come great responsibility. To save all of Marvel's New York, Miles must take up the mantle of Spider-Man and own it.",
      promo:"https://www.youtube.com/embed/NTunTURbyUU",
      details:"<div><div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 7 hours, Main + Extra - 12 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 85/100 </div> <div> <strong>Release Date: </strong>12 Nov 2020 </div> <div> <strong>Developer: </strong> Insomniac Games </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "NEW",
      other_loc:24,
      device:"PS4",
    },
    {
      id:13,
      img:"https://www.gamecards.net/wp-content/uploads/2020/07/Ghost-of-Tsushima-ps4.jpg",
      title: "Ghost Of Tsushima - PS4 (Pre-owned)",
      price: 2000,
      description: "<p>It’s the late 13th century, and the Mongol empire has laid waste to entire nations in its campaign to conquer the East. Tsushima Island is all that stands between mainland Japan and a massive Mongol invasion. <br>As the island burns in the wake of the first wave of the Mongol assault, samurai warrior Jin Sakai resolves to do whatever it takes to protect his people and reclaim his home. <br>• Beyond war, ancient beauty endures: Uncover the hidden wonders of Tsushima in this open-world action adventure. <br>• The rise of the Ghost: Forge a new path and wage an unconventional war for the freedom of Tsushima. <br>• Mud, blood and steel: Challenge opponents with your katana for an immersive samurai combat experience, master the bow to eliminate distant threats and develop stealth tactics to ambush enemies.</p>",
      promo: "https://www.youtube.com/embed/0HTfLqHoTmg",
      details: "<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 24.5 hours, Main + Extra - 43 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>Optional </div> <br> <div> <strong>Metacritic Review Score: </strong> 83/100 </div> <div> <strong>Release Date: </strong>17 Jul 2020 </div> <div> <strong>Developer: </strong> Sucker Punch Productions </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Product sourced from Individual in India as a pre-owned one </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:1,
      device:"PS4",
    },
    {
      id:14,
      img:"https://rukminim2.flixcart.com/image/416/416/kr3tj0w0/physical-game/c/f/u/standard-edition-ps4-minecraft-starter-collection-full-game-ps4-original-imag4ypx2qajzfgq.jpeg?q=70",
      title:"Minecraft Bedrock Edition - PS4 (Pre-owned)",
      price:1000,
      description:"<p>Explore randomly generated worlds and build amazing things from the simplest of homes to the grandest of castles. Play in creative mode with unlimited resources or mine deep into the world in survival mode, crafting weapons and armour to fend off the dangerous mobs.</p>",
      promo:"https://www.youtube.com/embed/5QYaQw0cQYI",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Adventure / Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 123 hours, Main + Extra - 281 hours </div> <div> <strong>Internet Requirement: </strong>Yes </div> <div> <strong>PS Plus Requirement: </strong>Optional </div> <br> <div> <strong>Metacritic Review Score: </strong> 89/100 </div> <div> <strong>Release Date: </strong>05 Sep 2014 </div> <div> <strong>Developer: </strong> Mojang Studios </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Sweden </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 7 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:2,
      device:"PS4",
    },
    {
      id:15,
      img:"https://rukminim2.flixcart.com/image/416/416/kw5ag7k0/physical-game/t/k/m/-original-imag8w4bg6mfssuh.jpeg?q=70",
      title:"God Of War - PS4 (Pre-owned)",
      price:500,
      description:"<p>Living as a man outside the shadow of the gods, Kratos must adapt to unfamiliar lands, unexpected threats and a second chance at being a father. Together with his son Atreus, the pair will venture into the brutal realm of Midgard and fight to fulfil a deeply personal quest. <br>• Journey to a dark, elemental world of fearsome creatures – straight from the pages of Norse mythology. <br>• Conquer your foes in vicious close-quarters combat that rewards tactical thinking and lethal precision. <br>• Discover an emotionally gripping tale of father and son, as Kratos is made to control the rage that has long defined him.</p>",
      promo:"https://www.youtube.com/embed/K0u_kAWLJOA",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 20.5 hours, Main + Extra - 32 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 94/100 </div> <div> <strong>Release Date: </strong>20 Apr 2018 </div> <div> <strong>Developer: </strong> Santa Monica Studio </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:3,
      device:"PS4",
    },
    {
      id:16,
      img:"https://rukminim2.flixcart.com/image/416/416/joixj0w0/physical-game/u/3/u/standard-edition-red-dead-redemption-2-full-game-ps4-original-imafayznnszyfn2h.jpeg?q=70",
      title:"Red Dead Redemption 2 - PS4 (Pre-owned)",
      price:1500,
      description:"<p>Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, Red Dead Redemption 2 is an epic tale of honor and loyalty at the dawn of the modern age. <br> <br>America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him. <br> <br>Red Dead Redemption 2 also includes the shared living world of Red Dead Online – forge your own path as you battle lawmen, outlaw gangs and ferocious wild animals to build a life on the American frontier. Build a camp, ride solo or form a posse and explore everything from the snowy mountains in the North to the swamps of the South, from remote outposts to busy farms and bustling towns. Chase down bounties, hunt, fish and trade, search for exotic treasures, run your own underground Moonshine distillery, or become a Naturalist to learn the secrets of the animal kingdom and much more in a world of astounding depth and detail.</p>",
      promo:"https://www.youtube.com/embed/h6k532Y7jK8",
      details:"<div> <div> <strong>Game Type: </strong> Campaign + Multiplayer </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 49 hours, Main + Extra - 78.5 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>Optional </div> <br> <div> <strong>Metacritic Review Score: </strong> 97/100 </div> <div> <strong>Release Date: </strong>26 Oct 2018 </div> <div> <strong>Developer: </strong> Rockstar Games </div> <div> <strong>Publisher: </strong> Rockstar Games </div> <div> <strong>Country of Origin: </strong>United States </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:4,
      device:"PS4",
    },
    {
      id:17,
      img:"https://rukminim2.flixcart.com/image/416/416/j5pmt8w0/physical-game/x/n/c/uncharted-the-nathan-drake-collection-ps4-original-imaer6qwcpz2p4qa.jpeg?q=70",
      title:"Uncharted - The Nathan Drake Collection - PS4 (Pre-owned)",
      price:1000,
      description:"<div> <p>Experience one of the most revered game series of all time as you follow the perilous journey of Nathan Drake across the globe, from humble beginnings to extraordinary discoveries. <br> <br>Meet an unforgettable cast of characters as Drake puts life and friendship on the line in a race against ruthless enemies to uncover unimaginable treasures. <br> <br>Uncharted: The Nathan Drake Collection includes the single-player campaigns only for Uncharted: Drake’s Fortune, Uncharted 2: Among Thieves, and Uncharted 3: Drake’s Deception.</p> </div>",
      promo:"https://www.youtube.com/embed/-mH2SVyBMAQ",
      details:"<div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 27 hours, Main + Extra - 31 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 86/100 </div> <div> <strong>Release Date: </strong>07 Oct 2015 </div> <div> <strong>Developer: </strong> Naughty Dog </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:5,
      device:"PS4",
    },
    {
      id:18,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1232",
      title:"Assassins Creed Valhalla - PS4 (Pre-owned)",
      price:3000,
      description:"<div> <p>Build your own Viking legend at 60 FPS and in 4K resolution. <br> <br>Become Eivor, a legendary Viking warrior raised on tales of battle and glory. Raid your enemies, grow your settlement, and build your political power in the quest to earn a place among the gods in Valhalla. <br> <br>- Lead epic Viking raids against Saxon troops and fortresses. <br>- Relive the visceral fighting style of the Vikings as you dual-wield powerful weapons. <br>- Challenge yourself with the most varied collection of enemies ever in Assassin's Creed. <br>- Shape the growth of your character and your clan's settlement with every choice you make. <br>- Explore a Dark Age open world, from the harsh shores of Norway to the beautiful kingdoms of England.</p> </div>",
      promo:"https://www.youtube.com/embed/gnmuEkn30ZE",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure / Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 52 hours, Main + Extra - 86 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 84/100 </div> <div> <strong>Release Date: </strong>10 Nov 2020 </div> <div> <strong>Developer: </strong> Ubisoft </div> <div> <strong>Publisher: </strong> Ubisoft </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:6,
      device:"PS4",
    },
    {
      id:19,
      img:"https://rukminim2.flixcart.com/image/416/416/jpa2w7k0/physical-game/z/a/d/standard-edition-tekken-7-full-game-ps4-original-imafbjxexwbsnb7j.jpeg?q=70",
      title:"Tekken 7 - PS4 (Pre-owned)",
      price:700,
      description:"<div> <p>Discover the epic conclusion of the Mishima clan and unravel the reasons behind each step of their ceaseless fight. Powered by Unreal Engine 4, TEKKEN 7 features stunning story-driven cinematic battles and intense duels that can be enjoyed with friends and rivals alike through innovative fight mechanics. <br> <br>Love, Revenge, Pride. Everyone has a reason to fight. Values are what define us and make us human, regardless of our strengths and weaknesses. There are no wrong motivations, just the path we choose to take. <br></p> </div>",
      promo:"https://www.youtube.com/embed/1V-_q3SKh5w",
      details:"<div><div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Fighting </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 3 hours, Main + Extra - 7 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>Optional </div> <br> <div> <strong>Metacritic Review Score: </strong> 82/100 </div> <div> <strong>Release Date: </strong>18 Mar 2015 </div> <div> <strong>Developer: </strong> Bandai Namco Studios </div> <div> <strong>Publisher: </strong> Bandai Namco Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:7,
      device:"PS4",
    },
    {
      id:20,
      img:"https://rukminim2.flixcart.com/image/416/416/av-media/games/f/f/m/the-last-of-us-remastered-original-imady9fcv5xe4kbf.jpeg?q=70",
      title:"The Last Of Us Remastered - PS4 (Pre-owned)",
      price:300,
      description:"<div> <p>In a hostile, post-pandemic world, Joel and Ellie, brought together by desperate circumstances, must rely on each other to survive a brutal journey across what remains of the USA. <br> <br> <br>Remastered Features: <br>• Explore a beautiful, decimated world, fully realised with the power of PlayStation4 in 1080p High Definition. <br>• Delve into Ellie’s past in Left Behind, a single-player prequel chapter. <br>• Fight for survival across the Abandoned and Reclaimed Territories with eight new multiplayer maps and a harder single-player difficulty mode. <br>• Behind-the-scenes in-game cinematic commentary from the cast and creative director.</p> </div>",
      promo:"https://www.youtube.com/embed/ygVPHxkokAE",
      details:"<div><div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 14 hours, Main + Extra - 17 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>Optional </div> <br> <div> <strong>Metacritic Review Score: </strong> 95/100 </div> <div> <strong>Release Date: </strong>14 Jun 2013 </div> <div> <strong>Developer: </strong> Naughty Dog </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Andorra </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:8,
      device:"PS4",
    },
    {
      id:21,
      img:"https://rukminim2.flixcart.com/image/416/416/ku1k4280/physical-game/f/s/w/no-complete-edition-horizon-zero-dawn-full-game-ps4-original-imag796pg9f7hqgs.jpeg?q=70",
      title:"Horizon Zero Dawn Complete Edition - PS4 (Pre-owned)",
      price:500,
      description:"<div> <p>EARTH IS OURS NO MORE <br> <br>Experience Aloy of the Nora’s entire legendary quest to unravel the mysteries of a world ruled by deadly Machines. <br> <br>An outcast from her tribe, the young hunter fights to uncover her past, discover her destiny… and stop a catastrophic threat to the future. <br> <br>Unleash devastating, tactical attacks against unique Machines and rival tribes as you explore an open wold teeming with wildlife and danger. <br> <br>Horizon Zero Dawn™ is a multi-award-winning action role-playing game – and this Complete Edition includes the huge expansion The Frozen Wilds, featuring new lands, skills, weapons and Machines. <br> <br>Enhanced for PlayStation®4 Pro. <br> <br>INCLUDES: <br>• Horizon Zero Dawn. <br>• The Frozen Wilds expansion. <br>• Carja Storm Ranger Outfit and Carja Mighty Bow. <br>• Carja Trader Pack. <br>• Banuk Trailblazer Outfit and Banuk Culling Bow. <br>• Banuk Traveller Pack. <br>• Nora Keeper Pack. <br>• Digital art book. <br>• PS4™ theme. <br> <br>Bonus costumes, weapons and item packs are available after downloading Horizon Zero Dawn: Complete Edition update file version 1.45 otherwise they are unlockable through gameplay.</p> </div>",
      promo:"https://www.youtube.com/embed/6Z1AGyzZbLM",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 31 hours, Main + Extra - 56 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 89/100 </div> <div> <strong>Release Date: </strong>06 Dec 2017 </div> <div> <strong>Developer: </strong> Guerrilla Games </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:9,
      device:"PS4",
    },
    {
      id:22,
      img:"https://m.media-amazon.com/images/I/518B2PBNkHL.jpg",
      title:"Marvel's Spiderman - PS4 (Pre-owned)",
      price:1000,
      description:"<div> <p>BE GREATER. <br> <br>Explore a new chapter in Marvel’s Spider-Man universe as a more experienced Peter Parker. <br> <br>Starring one of the world’s most iconic Super Heroes, Marvel's Spider-Man features the acrobatic abilities, improvisation and web-slinging that the wall-crawler is famous for, while also introducing elements never-before-seen in a Spider-Man game. <br> <br>From traversing by parkour and unique environmental interactions, to new combat and blockbuster action, it’s Spider-Man unlike any you’ve played before.</p> </div>",
      promo:"https://www.youtube.com/embed/b5-_MvCWSfI",
      details:"<div><div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 16 hours, Main + Extra - 24.5 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 87/100 </div> <div> <strong>Release Date: </strong>07 Sep 2018 </div> <div> <strong>Developer: </strong> Insomniac Games </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:10,
      device:"PS4",
    },
    {
      id:23,
      img:"https://m.media-amazon.com/images/I/71mrNn40chL._SX385_.jpg",
      title:"Elden Ring - PS4 (Pre-owned)",
      price:3800,
      description:"<p>The Golden Order has been broken. <br> <br>In the Lands Between ruled by Queen Marika the Eternal, the Elden Ring, the source of the Erdtree, has been shattered. <br> <br>Marika's offspring, demigods all, claimed the shards of the Elden Ring known as the Great Runes, and the mad taint of their newfound strength triggered a war: The Shattering. A war that meant abandonment by the Greater Will. <br> <br>And now the guidance of grace will be brought to the Tarnished who were spurned by the grace of gold and exiled from the Lands Between. <br> <br>Ye dead who yet live, your grace long lost, follow the path to the Lands Between beyond the foggy sea to stand before the Elden Ring. <br> <br>And become the Elden Lord.</p>",
      promo:"https://www.youtube.com/embed/E3Huy2cdih0",
      details:"<div><div> <strong>Game Type: </strong> Campaign + Multiplayer </div> <div> <strong>Genre: </strong> Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 44 hours, Main + Extra - 74.5 hours </div> <div> <strong>Internet Requirement: </strong>Yes </div> <div> <strong>PS Plus Requirement: </strong>Yes </div> <br> <div> <strong>Metacritic Review Score: </strong> 97/100 </div> <div> <strong>Release Date: </strong>25 Feb 2022 </div> <div> <strong>Developer: </strong> FromSoftware Inc </div> <div> <strong>Publisher: </strong> BANDAI NAMCO ENTERTAINMENT </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:11,
      device:"PS4",
    },
    {
      id:24,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_105",
      title:"Marvel's Spider-Man Miles Morales - PS4 (Pre-owned)",
      price:3250,
      description:"In the latest adventure in the Marvel's Spider-Man universe, teenager Miles Morales is adjusting to his new home while following in the footsteps of his mentor, Peter Parker, as a new Spider-Man. But when a fierce power struggle threatens to destroy his new home, the aspiring hero realises that with great power, there must also come great responsibility. To save all of Marvel's New York, Miles must take up the mantle of Spider-Man and own it.",
      promo:"https://www.youtube.com/embed/NTunTURbyUU",
      details:"<div><div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 7 hours, Main + Extra - 12 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 85/100 </div> <div> <strong>Release Date: </strong>12 Nov 2020 </div> <div> <strong>Developer: </strong> Insomniac Games </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:12,
      device:"PS4",
    },
    {
      id:25,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_482",
      title:"Red Dead Redemption 2 - Xbox One",
      price:2500,
      description:"<p>Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, Red Dead Redemption 2 is an epic tale of honor and loyalty at the dawn of the modern age. <br> <br>America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him. <br> <br>Red Dead Redemption 2 also includes the shared living world of Red Dead Online – forge your own path as you battle lawmen, outlaw gangs and ferocious wild animals to build a life on the American frontier. Build a camp, ride solo or form a posse and explore everything from the snowy mountains in the North to the swamps of the South, from remote outposts to busy farms and bustling towns. Chase down bounties, hunt, fish and trade, search for exotic treasures, run your own underground Moonshine distillery, or become a Naturalist to learn the secrets of the animal kingdom and much more in a world of astounding depth and detail.</p>",
      promo:"https://www.youtube.com/embed/kQfX6QgTnMg",
      details:"<div> <div> <strong>Game Type: </strong> Campaign + Multiplayer </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 49 hours, Main + Extra - 78.5 hours </div>  <br> <div> <strong>Metacritic Review Score: </strong> 97/100 </div> <div> <strong>Release Date: </strong>26 Oct 2018 </div> <div> <strong>Developer: </strong> Rockstar Games </div> <div> <strong>Publisher: </strong> Rockstar Games </div> <div> <strong>Country of Origin: </strong>United States </div> <div> <strong>Playable On: </strong> Xbox One, Xbox Series X </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "NEW",
      other_loc:33,
      device:"Xbox OneS",
    },
    
    {
      id:26,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_495",
      title:"Tekken 7 - Xbox One",
      price:1700,
      description:"<div> <p>Discover the epic conclusion of the Mishima clan and unravel the reasons behind each step of their ceaseless fight. Powered by Unreal Engine 4, TEKKEN 7 features stunning story-driven cinematic battles and intense duels that can be enjoyed with friends and rivals alike through innovative fight mechanics. <br> <br>Love, Revenge, Pride. Everyone has a reason to fight. Values are what define us and make us human, regardless of our strengths and weaknesses. There are no wrong motivations, just the path we choose to take. <br></p> </div>",
      promo:"https://www.youtube.com/embed/HBSPyfYCkIY",
      details:"<div><div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Fighting </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 3 hours, Main + Extra - 7 hours </div><br> <div> <strong>Metacritic Review Score: </strong> 82/100 </div> <div> <strong>Release Date: </strong>18 Mar 2015 </div> <div> <strong>Developer: </strong> Bandai Namco Studios </div> <div> <strong>Publisher: </strong> Bandai Namco Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> Xbox One, Xbox Series X </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "NEW",
      other_loc:34,
      device:"Xbox OneS",
    },
    {
      id:27,
      img:"https://cdn-products.eneba.com/resized-products/Qpp1Loj7MqjZI3SanQJvzZc7WwVCsyF0i1Ty925544A_350x200_1x-0.png",
      title:"Elden Ring - Xbox One",
      price:4000,
      description:"<p>The Golden Order has been broken. <br> <br>In the Lands Between ruled by Queen Marika the Eternal, the Elden Ring, the source of the Erdtree, has been shattered. <br> <br>Marika's offspring, demigods all, claimed the shards of the Elden Ring known as the Great Runes, and the mad taint of their newfound strength triggered a war: The Shattering. A war that meant abandonment by the Greater Will. <br> <br>And now the guidance of grace will be brought to the Tarnished who were spurned by the grace of gold and exiled from the Lands Between. <br> <br>Ye dead who yet live, your grace long lost, follow the path to the Lands Between beyond the foggy sea to stand before the Elden Ring. <br> <br>And become the Elden Lord.</p>",
      promo:"https://www.youtube.com/embed/E3Huy2cdih0",
      details:"<div><div> <strong>Game Type: </strong> Campaign + Multiplayer </div> <div> <strong>Genre: </strong> Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 44 hours, Main + Extra - 74.5 hours </div> <br> <div> <strong>Metacritic Review Score: </strong> 97/100 </div> <div> <strong>Release Date: </strong>25 Feb 2022 </div> <div> <strong>Developer: </strong> FromSoftware Inc </div> <div> <strong>Publisher: </strong> BANDAI NAMCO ENTERTAINMENT </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> Xbox One, Xbox Series X </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "NEW",
      other_loc:35,
      device:"Xbox OneS",
    },
    
    {
      id:28,
      img:"https://m.media-amazon.com/images/I/81439KxmiAL._SL1500_.jpg",
      title:"Assassins Creed Valhalla - Xbox One",
      price:3000,
      description:"<div> <p>Build your own Viking legend at 60 FPS and in 4K resolution. <br> <br>Become Eivor, a legendary Viking warrior raised on tales of battle and glory. Raid your enemies, grow your settlement, and build your political power in the quest to earn a place among the gods in Valhalla. <br> <br>- Lead epic Viking raids against Saxon troops and fortresses. <br>- Relive the visceral fighting style of the Vikings as you dual-wield powerful weapons. <br>- Challenge yourself with the most varied collection of enemies ever in Assassin's Creed. <br>- Shape the growth of your character and your clan's settlement with every choice you make. <br>- Explore a Dark Age open world, from the harsh shores of Norway to the beautiful kingdoms of England.</p> </div>",
      promo:"https://www.youtube.com/embed/ssrNcwxALS4",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure / Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 52 hours, Main + Extra - 86 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 84/100 </div> <div> <strong>Release Date: </strong>10 Nov 2020 </div> <div> <strong>Developer: </strong> Ubisoft </div> <div> <strong>Publisher: </strong> Ubisoft </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "NEW",
      other_loc:36,
      device:"Xbox OneS",
    },
    {
      id:29,
      img:"https://store-images.s-microsoft.com/image/apps.34695.68182501197884443.ac728a87-7bc1-4a0d-8bc6-0712072da93c.25816f86-f27c-4ade-ae29-222661145f1f",
      title:"Red Dead Redemption 2 - Xbox Series X",
      price:2500,
      description:"<p>Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, Red Dead Redemption 2 is an epic tale of honor and loyalty at the dawn of the modern age. <br> <br>America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him. <br> <br>Red Dead Redemption 2 also includes the shared living world of Red Dead Online – forge your own path as you battle lawmen, outlaw gangs and ferocious wild animals to build a life on the American frontier. Build a camp, ride solo or form a posse and explore everything from the snowy mountains in the North to the swamps of the South, from remote outposts to busy farms and bustling towns. Chase down bounties, hunt, fish and trade, search for exotic treasures, run your own underground Moonshine distillery, or become a Naturalist to learn the secrets of the animal kingdom and much more in a world of astounding depth and detail.</p>",
      promo:"https://www.youtube.com/embed/kQfX6QgTnMg",
      details:"<div> <div> <strong>Game Type: </strong> Campaign + Multiplayer </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 49 hours, Main + Extra - 78.5 hours </div>  <br> <div> <strong>Metacritic Review Score: </strong> 97/100 </div> <div> <strong>Release Date: </strong>26 Oct 2018 </div> <div> <strong>Developer: </strong> Rockstar Games </div> <div> <strong>Publisher: </strong> Rockstar Games </div> <div> <strong>Country of Origin: </strong>United States </div> <div> <strong>Playable On: </strong> Xbox One, Xbox Series X </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "NEW",
      other_loc:37,
      device:"Xbox Series X",
    },
    
    {
      id:30,
      img:"https://static.raru.co.za/cover/2021/12/17/9194957-l.jpg?v=1639738680",
      title:"Tekken 7 - Xbox Series X",
      price:1700,
      description:"<div> <p>Discover the epic conclusion of the Mishima clan and unravel the reasons behind each step of their ceaseless fight. Powered by Unreal Engine 4, TEKKEN 7 features stunning story-driven cinematic battles and intense duels that can be enjoyed with friends and rivals alike through innovative fight mechanics. <br> <br>Love, Revenge, Pride. Everyone has a reason to fight. Values are what define us and make us human, regardless of our strengths and weaknesses. There are no wrong motivations, just the path we choose to take. <br></p> </div>",
      promo:"https://www.youtube.com/embed/HBSPyfYCkIY",
      details:"<div><div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Fighting </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 3 hours, Main + Extra - 7 hours </div><br> <div> <strong>Metacritic Review Score: </strong> 82/100 </div> <div> <strong>Release Date: </strong>18 Mar 2015 </div> <div> <strong>Developer: </strong> Bandai Namco Studios </div> <div> <strong>Publisher: </strong> Bandai Namco Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> Xbox One, Xbox Series X </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "NEW",
      other_loc:38,
      device:"Xbox Series X",
    },
    {
      id:31,
      img:"https://cdn-products.eneba.com/resized-products/Qpp1Loj7MqjZI3SanQJvzZc7WwVCsyF0i1Ty925544A_350x200_1x-0.png",
      title:"Elden Ring - Xbox Series X",
      price:4000,
      description:"<p>The Golden Order has been broken. <br> <br>In the Lands Between ruled by Queen Marika the Eternal, the Elden Ring, the source of the Erdtree, has been shattered. <br> <br>Marika's offspring, demigods all, claimed the shards of the Elden Ring known as the Great Runes, and the mad taint of their newfound strength triggered a war: The Shattering. A war that meant abandonment by the Greater Will. <br> <br>And now the guidance of grace will be brought to the Tarnished who were spurned by the grace of gold and exiled from the Lands Between. <br> <br>Ye dead who yet live, your grace long lost, follow the path to the Lands Between beyond the foggy sea to stand before the Elden Ring. <br> <br>And become the Elden Lord.</p>",
      promo:"https://www.youtube.com/embed/E3Huy2cdih0",
      details:"<div><div> <strong>Game Type: </strong> Campaign + Multiplayer </div> <div> <strong>Genre: </strong> Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 44 hours, Main + Extra - 74.5 hours </div> <br> <div> <strong>Metacritic Review Score: </strong> 97/100 </div> <div> <strong>Release Date: </strong>25 Feb 2022 </div> <div> <strong>Developer: </strong> FromSoftware Inc </div> <div> <strong>Publisher: </strong> BANDAI NAMCO ENTERTAINMENT </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> Xbox One, Xbox Series X </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "NEW",
      other_loc:39,
      device:"Xbox Series X",
    },
    
    {
      id:32,
      img:"https://m.media-amazon.com/images/I/81439KxmiAL._SL1500_.jpg",
      title:"Assassins Creed Valhalla - Xbox Series X",
      price:3000,
      description:"<div> <p>Build your own Viking legend at 60 FPS and in 4K resolution. <br> <br>Become Eivor, a legendary Viking warrior raised on tales of battle and glory. Raid your enemies, grow your settlement, and build your political power in the quest to earn a place among the gods in Valhalla. <br> <br>- Lead epic Viking raids against Saxon troops and fortresses. <br>- Relive the visceral fighting style of the Vikings as you dual-wield powerful weapons. <br>- Challenge yourself with the most varied collection of enemies ever in Assassin's Creed. <br>- Shape the growth of your character and your clan's settlement with every choice you make. <br>- Explore a Dark Age open world, from the harsh shores of Norway to the beautiful kingdoms of England.</p> </div>",
      promo:"https://www.youtube.com/embed/ssrNcwxALS4",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure / Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 52 hours, Main + Extra - 86 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 84/100 </div> <div> <strong>Release Date: </strong>10 Nov 2020 </div> <div> <strong>Developer: </strong> Ubisoft </div> <div> <strong>Publisher: </strong> Ubisoft </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "NEW",
      other_loc:40,
      device:"Xbox Series X",
    },
    {
      id:33,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_482",
      title:"Red Dead Redemption 2 - Xbox One (Pre-owned)",
      price:1500,
      description:"<p>Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, Red Dead Redemption 2 is an epic tale of honor and loyalty at the dawn of the modern age. <br> <br>America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him. <br> <br>Red Dead Redemption 2 also includes the shared living world of Red Dead Online – forge your own path as you battle lawmen, outlaw gangs and ferocious wild animals to build a life on the American frontier. Build a camp, ride solo or form a posse and explore everything from the snowy mountains in the North to the swamps of the South, from remote outposts to busy farms and bustling towns. Chase down bounties, hunt, fish and trade, search for exotic treasures, run your own underground Moonshine distillery, or become a Naturalist to learn the secrets of the animal kingdom and much more in a world of astounding depth and detail.</p>",
      promo:"https://www.youtube.com/embed/kQfX6QgTnMg",
      details:"<div> <div> <strong>Game Type: </strong> Campaign + Multiplayer </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 49 hours, Main + Extra - 78.5 hours </div>  <br> <div> <strong>Metacritic Review Score: </strong> 97/100 </div> <div> <strong>Release Date: </strong>26 Oct 2018 </div> <div> <strong>Developer: </strong> Rockstar Games </div> <div> <strong>Publisher: </strong> Rockstar Games </div> <div> <strong>Country of Origin: </strong>United States </div> <div> <strong>Playable On: </strong> Xbox One, Xbox Series X </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:25,
      device:"Xbox OneS",
    },
    
    {
      id:34,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_495",
      title:"Tekken 7 - Xbox One (Pre-owned)",
      price:700,
      description:"<div> <p>Discover the epic conclusion of the Mishima clan and unravel the reasons behind each step of their ceaseless fight. Powered by Unreal Engine 4, TEKKEN 7 features stunning story-driven cinematic battles and intense duels that can be enjoyed with friends and rivals alike through innovative fight mechanics. <br> <br>Love, Revenge, Pride. Everyone has a reason to fight. Values are what define us and make us human, regardless of our strengths and weaknesses. There are no wrong motivations, just the path we choose to take. <br></p> </div>",
      promo:"https://www.youtube.com/embed/HBSPyfYCkIY",
      details:"<div><div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Fighting </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 3 hours, Main + Extra - 7 hours </div><br> <div> <strong>Metacritic Review Score: </strong> 82/100 </div> <div> <strong>Release Date: </strong>18 Mar 2015 </div> <div> <strong>Developer: </strong> Bandai Namco Studios </div> <div> <strong>Publisher: </strong> Bandai Namco Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> Xbox One, Xbox Series X </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:26,
      device:"Xbox OneS",
    },
    {
      id:35,
      img:"https://cdn-products.eneba.com/resized-products/Qpp1Loj7MqjZI3SanQJvzZc7WwVCsyF0i1Ty925544A_350x200_1x-0.png",
      title:"Elden Ring - Xbox One (Pre-owned)",
      price:3000,
      description:"<p>The Golden Order has been broken. <br> <br>In the Lands Between ruled by Queen Marika the Eternal, the Elden Ring, the source of the Erdtree, has been shattered. <br> <br>Marika's offspring, demigods all, claimed the shards of the Elden Ring known as the Great Runes, and the mad taint of their newfound strength triggered a war: The Shattering. A war that meant abandonment by the Greater Will. <br> <br>And now the guidance of grace will be brought to the Tarnished who were spurned by the grace of gold and exiled from the Lands Between. <br> <br>Ye dead who yet live, your grace long lost, follow the path to the Lands Between beyond the foggy sea to stand before the Elden Ring. <br> <br>And become the Elden Lord.</p>",
      promo:"https://www.youtube.com/embed/E3Huy2cdih0",
      details:"<div><div> <strong>Game Type: </strong> Campaign + Multiplayer </div> <div> <strong>Genre: </strong> Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 44 hours, Main + Extra - 74.5 hours </div> <br> <div> <strong>Metacritic Review Score: </strong> 97/100 </div> <div> <strong>Release Date: </strong>25 Feb 2022 </div> <div> <strong>Developer: </strong> FromSoftware Inc </div> <div> <strong>Publisher: </strong> BANDAI NAMCO ENTERTAINMENT </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> Xbox One, Xbox Series X </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:27,
      device:"Xbox OneS",
    },
    {
      id:36,
      img:"https://m.media-amazon.com/images/I/81439KxmiAL._SL1500_.jpg",
      title:"Assassins Creed Valhalla - Xbox One (Pre-owned)",
      price:2000,
      description:"<div> <p>Build your own Viking legend at 60 FPS and in 4K resolution. <br> <br>Become Eivor, a legendary Viking warrior raised on tales of battle and glory. Raid your enemies, grow your settlement, and build your political power in the quest to earn a place among the gods in Valhalla. <br> <br>- Lead epic Viking raids against Saxon troops and fortresses. <br>- Relive the visceral fighting style of the Vikings as you dual-wield powerful weapons. <br>- Challenge yourself with the most varied collection of enemies ever in Assassin's Creed. <br>- Shape the growth of your character and your clan's settlement with every choice you make. <br>- Explore a Dark Age open world, from the harsh shores of Norway to the beautiful kingdoms of England.</p> </div>",
      promo:"https://www.youtube.com/embed/ssrNcwxALS4",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure / Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 52 hours, Main + Extra - 86 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 84/100 </div> <div> <strong>Release Date: </strong>10 Nov 2020 </div> <div> <strong>Developer: </strong> Ubisoft </div> <div> <strong>Publisher: </strong> Ubisoft </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:28,
      device:"Xbox OneS",
    },
    {
      id:37,
      img:"https://store-images.s-microsoft.com/image/apps.34695.68182501197884443.ac728a87-7bc1-4a0d-8bc6-0712072da93c.25816f86-f27c-4ade-ae29-222661145f1f",
      title:"Red Dead Redemption 2 - Xbox Series X (Pre-owned)",
      price:1500,
      description:"<p>Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, Red Dead Redemption 2 is an epic tale of honor and loyalty at the dawn of the modern age. <br> <br>America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him. <br> <br>Red Dead Redemption 2 also includes the shared living world of Red Dead Online – forge your own path as you battle lawmen, outlaw gangs and ferocious wild animals to build a life on the American frontier. Build a camp, ride solo or form a posse and explore everything from the snowy mountains in the North to the swamps of the South, from remote outposts to busy farms and bustling towns. Chase down bounties, hunt, fish and trade, search for exotic treasures, run your own underground Moonshine distillery, or become a Naturalist to learn the secrets of the animal kingdom and much more in a world of astounding depth and detail.</p>",
      promo:"https://www.youtube.com/embed/kQfX6QgTnMg",
      details:"<div> <div> <strong>Game Type: </strong> Campaign + Multiplayer </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 49 hours, Main + Extra - 78.5 hours </div>  <br> <div> <strong>Metacritic Review Score: </strong> 97/100 </div> <div> <strong>Release Date: </strong>26 Oct 2018 </div> <div> <strong>Developer: </strong> Rockstar Games </div> <div> <strong>Publisher: </strong> Rockstar Games </div> <div> <strong>Country of Origin: </strong>United States </div> <div> <strong>Playable On: </strong> Xbox One, Xbox Series X </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:29,
      device:"Xbox Series X",
    },
    
    {
      id:38,
      img:"https://static.raru.co.za/cover/2021/12/17/9194957-l.jpg?v=1639738680",
      title:"Tekken 7 - Xbox Series X (Pre-owned)",
      price:700,
      description:"<div> <p>Discover the epic conclusion of the Mishima clan and unravel the reasons behind each step of their ceaseless fight. Powered by Unreal Engine 4, TEKKEN 7 features stunning story-driven cinematic battles and intense duels that can be enjoyed with friends and rivals alike through innovative fight mechanics. <br> <br>Love, Revenge, Pride. Everyone has a reason to fight. Values are what define us and make us human, regardless of our strengths and weaknesses. There are no wrong motivations, just the path we choose to take. <br></p> </div>",
      promo:"https://www.youtube.com/embed/HBSPyfYCkIY",
      details:"<div><div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Fighting </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 3 hours, Main + Extra - 7 hours </div><br> <div> <strong>Metacritic Review Score: </strong> 82/100 </div> <div> <strong>Release Date: </strong>18 Mar 2015 </div> <div> <strong>Developer: </strong> Bandai Namco Studios </div> <div> <strong>Publisher: </strong> Bandai Namco Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> Xbox One, Xbox Series X </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:30,
      device:"Xbox Series X",
    },
    {
      id:39,
      img:"https://cdn-products.eneba.com/resized-products/Qpp1Loj7MqjZI3SanQJvzZc7WwVCsyF0i1Ty925544A_350x200_1x-0.png",
      title:"Elden Ring - Xbox Series X (Pre-owned)",
      price:3000,
      description:"<p>The Golden Order has been broken. <br> <br>In the Lands Between ruled by Queen Marika the Eternal, the Elden Ring, the source of the Erdtree, has been shattered. <br> <br>Marika's offspring, demigods all, claimed the shards of the Elden Ring known as the Great Runes, and the mad taint of their newfound strength triggered a war: The Shattering. A war that meant abandonment by the Greater Will. <br> <br>And now the guidance of grace will be brought to the Tarnished who were spurned by the grace of gold and exiled from the Lands Between. <br> <br>Ye dead who yet live, your grace long lost, follow the path to the Lands Between beyond the foggy sea to stand before the Elden Ring. <br> <br>And become the Elden Lord.</p>",
      promo:"https://www.youtube.com/embed/E3Huy2cdih0",
      details:"<div><div> <strong>Game Type: </strong> Campaign + Multiplayer </div> <div> <strong>Genre: </strong> Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 44 hours, Main + Extra - 74.5 hours </div> <br> <div> <strong>Metacritic Review Score: </strong> 97/100 </div> <div> <strong>Release Date: </strong>25 Feb 2022 </div> <div> <strong>Developer: </strong> FromSoftware Inc </div> <div> <strong>Publisher: </strong> BANDAI NAMCO ENTERTAINMENT </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> Xbox One, Xbox Series X </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:31,
      device:"Xbox Series X",
    },
    
    {
      id:40,
      img:"https://m.media-amazon.com/images/I/81439KxmiAL._SL1500_.jpg",
      title:"Assassins Creed Valhalla - Xbox Series X (Pre-owned)",
      price:2000,
      description:"<div> <p>Build your own Viking legend at 60 FPS and in 4K resolution. <br> <br>Become Eivor, a legendary Viking warrior raised on tales of battle and glory. Raid your enemies, grow your settlement, and build your political power in the quest to earn a place among the gods in Valhalla. <br> <br>- Lead epic Viking raids against Saxon troops and fortresses. <br>- Relive the visceral fighting style of the Vikings as you dual-wield powerful weapons. <br>- Challenge yourself with the most varied collection of enemies ever in Assassin's Creed. <br>- Shape the growth of your character and your clan's settlement with every choice you make. <br>- Explore a Dark Age open world, from the harsh shores of Norway to the beautiful kingdoms of England.</p> </div>",
      promo:"https://www.youtube.com/embed/ssrNcwxALS4",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure / Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 52 hours, Main + Extra - 86 hours </div> <div> <strong>Internet Requirement: </strong>No </div> <div> <strong>PS Plus Requirement: </strong>No </div> <br> <div> <strong>Metacritic Review Score: </strong> 84/100 </div> <div> <strong>Release Date: </strong>10 Nov 2020 </div> <div> <strong>Developer: </strong> Ubisoft </div> <div> <strong>Publisher: </strong> Ubisoft </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> PS4, PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:32,
      device:"Xbox Series X",
    },
    {
      id:41,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_692",
      title: "Marvel's Spider-Man: Miles Morales - PS5",
      price: 4000,
      description: "<div> <p>In the latest adventure in the Marvel's Spider-Man universe, teenager Miles Morales is adjusting to his new home while following in the footsteps of his mentor, Peter Parker, as a new Spider-Man. But when a fierce power struggle threatens to destroy his new home, the aspiring hero realises that with great power, there must also come great responsibility. To save all of Marvel's New York, Miles must take up the mantle of Spider-Man and own it.</p> </div>",
      promo: "https://www.youtube.com/embed/NTunTURbyUU",
      
      details: "<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 7.5 hours, Main + Extra - 12 hours </div> <br> <div> <strong>Metacritic Review Score: </strong> 85/100 </div> <div> <strong>Release Date: </strong>12 Nov 2020 </div> <div> <strong>Developer: </strong> Insomniac Games </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "NEW",
      other_loc:45,
      device:"PS5",
    },
    {
      id:42,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_686",
      title:"Assassin's Creed Valhalla - PS5",
      price:4000,
      description:"<p>Become Eivor, a legendary Viking warrior raised on tales of battle and glory. Raid your enemies, grow your settlement, and build your political power in the quest to earn a place among the gods in Valhalla. <br> <br>- Lead epic Viking raids against Saxon troops and fortresses. <br>- Relive the visceral fighting style of the Vikings as you dual-wield powerful weapons. <br>- Challenge yourself with the most varied collection of enemies ever in Assassin's Creed. <br>- Shape the growth of your character and your clan's settlement with every choice you make. <br>- Explore a Dark Age open world, from the harsh shores of Norway to the beautiful kingdoms of England.</p>",
      promo:"https://www.youtube.com/embed/gnmuEkn30ZE",
      details:"<div > <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 53 hours, Main + Extra - 86 hours </div> <br> <div> <strong>Metacritic Review Score: </strong> 84/100 </div> <div> <strong>Release Date: </strong>12 Nov 2020 </div> <div> <strong>Developer: </strong> Ubisoft </div> <div> <strong>Publisher: </strong> Ubisoft </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "NEW",
      other_loc:46,
      device:"PS5",
    },
    {
      id:43,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_693",
      title:"Mortal Kombat 11 Ultimate Edition - PS5",
      price:3000,
      description:"<p>The definitive MK11 experience! Take control of Earthrealm's protectors in the game's TWO critically acclaimed, time-bending Story Campaigns as they race to stop Kronika from rewinding time and rebooting history. Friendships are tested, and new alliances forged, in the battle to save all of existence. MK11 Ultimate features the komplete 37-character roster, including new additions Rain, Mileena &amp; Rambo. <br> <br>Mortal Kombat 11 showcases every amusing friendship, gory fatality and soul-crushing fatal blow like never before. You'll be so close to the fight, you can feel it! <br> <br>Includes Mortal Kombat 11, Kombat Pack 1, Aftermath Expansion &amp; Kombat Pack 2. <br> <br>• Experience 2 robust, critically acclaimed Story Campaigns from MK11 &amp; MK11: Aftermath <br>• Play as the komplete 37-character roster including newly added fighters Mileena, Rain &amp; Rambo <br>• Thousands of skins, weapons &amp; gear for an unprecedented level of fighter customization <br>• Includes all previous guest fighters: Terminator, Joker, Spawn &amp; RoboCop <br>• Every mode including Towers of Time, Krypt, Tutorial, Online, Klassic Towers &amp; more <br>• All Stages, Stage Fatalities, Brutalities, Iconic Fatalities &amp; Friendships</p>",
      promo:"https://www.youtube.com/embed/OEQsQqkEKMA",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Fighting </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 8 hours, Main + Extra - 9.5 hours </div> <br> <div> <strong>Metacritic Review Score: </strong> 87/100 </div> <div> <strong>Release Date: </strong>18 Nov 2020 </div> <div> <strong>Developer: </strong> NetherRealm Studios </div> <div> <strong>Publisher: </strong> Warner Bros. Interactive </div> <div> <strong>Country of Origin: </strong>United States </div> <div> <strong>Playable On: </strong> PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "NEW",
      other_loc:47,
      device:"PS5",
    },
    {
      id:44,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_697",
      title:"The Pathless - PS5",
      price:4300,
      description:"<p>From the creators of ABZÛ, The Pathless is the mythic adventure of an archer and an eagle in a vast forest. <br> <br>Archery and Falconry <br> <br>Become the Hunter, a master of archery who travels to a mystical island to dispel a curse of darkness that grips the world. Forge a connection with your eagle companion and soar through the air. Perform fluid acrobatics and execute awesome trick shots with a unique archery system that allows effortless shooting while moving at high speeds. <br> <br>Explore an Open World <br> <br>Forge your own path through a beautiful open world packed with secrets to find. Traverse misty forests, lush meadows and snowy tundras. Discover the dark history of the island as you solve puzzles in ancient ruins and unearth long-forgotten secrets. <br> <br>Hunt Corrupted Spirits <br> <br>Giant corrupted spirits lurk in the woods. Use all your skill to hunt them down, but be careful not to become the hunted yourself. Engage in epic battles against the cursed beasts to restore light to the land. The bond with your eagle and the fate of the world hang in the balance.</p>",
      promo:"https://www.youtube.com/embed/4m73BSovpEc",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 6 hours, Main + Extra - 10 hours </div> <br> <div> <strong>Metacritic Review Score: </strong> 77/100 </div> <div> <strong>Release Date: </strong>12 Nov 2020 </div> <div> <strong>Developer: </strong> Giant Squid </div> <div> <strong>Publisher: </strong> Annapurna Interactive </div> <div> <strong>Country of Origin: </strong>United States </div> <div> <strong>Playable On: </strong> PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 12 and over </div> </div>",
      condition: "NEW",
      other_loc:48,
      device:"PS5",
    },
    {
      id:45,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_692",
      title: "Marvel's Spider-Man: Miles Morales - PS5 (Pre-owned)",
      price: 3000,
      description: "<div> <p>In the latest adventure in the Marvel's Spider-Man universe, teenager Miles Morales is adjusting to his new home while following in the footsteps of his mentor, Peter Parker, as a new Spider-Man. But when a fierce power struggle threatens to destroy his new home, the aspiring hero realises that with great power, there must also come great responsibility. To save all of Marvel's New York, Miles must take up the mantle of Spider-Man and own it.</p> </div>",
      promo: "https://www.youtube.com/embed/NTunTURbyUU",
      
      details: "<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 7.5 hours, Main + Extra - 12 hours </div> <br> <div> <strong>Metacritic Review Score: </strong> 85/100 </div> <div> <strong>Release Date: </strong>12 Nov 2020 </div> <div> <strong>Developer: </strong> Insomniac Games </div> <div> <strong>Publisher: </strong> Sony Interactive Entertainment </div> <div> <strong>Country of Origin: </strong>Japan </div> <div> <strong>Playable On: </strong> PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 16 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:41,
      device:"PS5",
    },
    {
      id:46,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_686",
      title:"Assassin's Creed Valhalla - PS5 (Pre-owned)",
      price:3000,
      description:"<p>Become Eivor, a legendary Viking warrior raised on tales of battle and glory. Raid your enemies, grow your settlement, and build your political power in the quest to earn a place among the gods in Valhalla. <br> <br>- Lead epic Viking raids against Saxon troops and fortresses. <br>- Relive the visceral fighting style of the Vikings as you dual-wield powerful weapons. <br>- Challenge yourself with the most varied collection of enemies ever in Assassin's Creed. <br>- Shape the growth of your character and your clan's settlement with every choice you make. <br>- Explore a Dark Age open world, from the harsh shores of Norway to the beautiful kingdoms of England.</p>",
      promo:"https://www.youtube.com/embed/gnmuEkn30ZE",
      details:"<div > <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Role Playing </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 53 hours, Main + Extra - 86 hours </div> <br> <div> <strong>Metacritic Review Score: </strong> 84/100 </div> <div> <strong>Release Date: </strong>12 Nov 2020 </div> <div> <strong>Developer: </strong> Ubisoft </div> <div> <strong>Publisher: </strong> Ubisoft </div> <div> <strong>Country of Origin: </strong>France </div> <div> <strong>Playable On: </strong> PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:42,
      device:"PS5",
    },
    {
      id:47,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_693",
      title:"Mortal Kombat 11 Ultimate Edition - PS5 (Pre-owned)",
      price:2000,
      description:"<p>The definitive MK11 experience! Take control of Earthrealm's protectors in the game's TWO critically acclaimed, time-bending Story Campaigns as they race to stop Kronika from rewinding time and rebooting history. Friendships are tested, and new alliances forged, in the battle to save all of existence. MK11 Ultimate features the komplete 37-character roster, including new additions Rain, Mileena &amp; Rambo. <br> <br>Mortal Kombat 11 showcases every amusing friendship, gory fatality and soul-crushing fatal blow like never before. You'll be so close to the fight, you can feel it! <br> <br>Includes Mortal Kombat 11, Kombat Pack 1, Aftermath Expansion &amp; Kombat Pack 2. <br> <br>• Experience 2 robust, critically acclaimed Story Campaigns from MK11 &amp; MK11: Aftermath <br>• Play as the komplete 37-character roster including newly added fighters Mileena, Rain &amp; Rambo <br>• Thousands of skins, weapons &amp; gear for an unprecedented level of fighter customization <br>• Includes all previous guest fighters: Terminator, Joker, Spawn &amp; RoboCop <br>• Every mode including Towers of Time, Krypt, Tutorial, Online, Klassic Towers &amp; more <br>• All Stages, Stage Fatalities, Brutalities, Iconic Fatalities &amp; Friendships</p>",
      promo:"https://www.youtube.com/embed/OEQsQqkEKMA",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Fighting </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 8 hours, Main + Extra - 9.5 hours </div> <br> <div> <strong>Metacritic Review Score: </strong> 87/100 </div> <div> <strong>Release Date: </strong>18 Nov 2020 </div> <div> <strong>Developer: </strong> NetherRealm Studios </div> <div> <strong>Publisher: </strong> Warner Bros. Interactive </div> <div> <strong>Country of Origin: </strong>United States </div> <div> <strong>Playable On: </strong> PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 18 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:43,
      device:"PS5",
    },
    {
      id:48,
      img:"https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_697",
      title:"The Pathless - PS5 (Pre-owned)",
      price:3300,
      description:"<p>From the creators of ABZÛ, The Pathless is the mythic adventure of an archer and an eagle in a vast forest. <br> <br>Archery and Falconry <br> <br>Become the Hunter, a master of archery who travels to a mystical island to dispel a curse of darkness that grips the world. Forge a connection with your eagle companion and soar through the air. Perform fluid acrobatics and execute awesome trick shots with a unique archery system that allows effortless shooting while moving at high speeds. <br> <br>Explore an Open World <br> <br>Forge your own path through a beautiful open world packed with secrets to find. Traverse misty forests, lush meadows and snowy tundras. Discover the dark history of the island as you solve puzzles in ancient ruins and unearth long-forgotten secrets. <br> <br>Hunt Corrupted Spirits <br> <br>Giant corrupted spirits lurk in the woods. Use all your skill to hunt them down, but be careful not to become the hunted yourself. Engage in epic battles against the cursed beasts to restore light to the land. The bond with your eagle and the fate of the world hang in the balance.</p>",
      promo:"https://www.youtube.com/embed/4m73BSovpEc",
      details:"<div> <div> <strong>Game Type: </strong> Campaign </div> <div> <strong>Genre: </strong> Action / Adventure </div> <div> <strong>Approx Gameplay Hours: </strong> Main Story - 6 hours, Main + Extra - 10 hours </div> <br> <div> <strong>Metacritic Review Score: </strong> 77/100 </div> <div> <strong>Release Date: </strong>12 Nov 2020 </div> <div> <strong>Developer: </strong> Giant Squid </div> <div> <strong>Publisher: </strong> Annapurna Interactive </div> <div> <strong>Country of Origin: </strong>United States </div> <div> <strong>Playable On: </strong> PS5 </div> <div> <strong>PEGI Rating: </strong> Ages 12 and over </div> </div>",
      condition: "PREOWNED",
      other_loc:44,
      device:"PS5",
    },
  ]

 